#
# This source file is part of the Stanford Biodesign for Digital Health open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#


name: 'SwiftLint Tool'
description: 'A tool to enforce Swift style and conventions using the official image.'
author: 'Andreas Bauer <mail@andi-bauer.com>'
branding:
  icon: 'terminal'
  color: 'green'

inputs:
  version:
    description: "A SwiftLint version to use."
    required: true
    default: 'latest'
  args:
    description: "Arguments to SwiftLint."
    required: false
  working-directory:
    description: "The working directory relative to the base `checkout` directory"
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo SL_VERSION=${{ inputs.version }} >> $GITHUB_ENV
    - name: Download SwiftLint
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        if [ "${{ runner.os }}" = macOS ]; then
          if [ "${{ inputs.version }}" = "latest" ]; then
            SWIFTLINT_URL="https://github.com/realm/SwiftLint/releases/latest/download/portable_swiftlint.zip"
          else
            SWIFTLINT_URL="https://github.com/realm/SwiftLint/releases/download/${{ inputs.version }}/portable_swiftlint.zip"
          fi
        elif [ "${{ runner.os }}" = Linux ]; then
          if [ "${{ inputs.version }}" = "latest" ]; then
            SWIFTLINT_URL="https://github.com/realm/SwiftLint/releases/latest/download/swiftlint_linux_amd64.zip"
          elif [ "${{ inputs.version}}" < "0.60.0" ]; then
            SWIFTLINT_URL="https://github.com/realm/SwiftLint/releases/download/${{ inputs.version }}/swiftlint_linux.zip"
          else
            SWIFTLINT_URL="https://github.com/realm/SwiftLint/releases/download/${{ inputs.version }}/swiftlint_linux_amd64.zip"
          fi
        else
          echo "Unsupported platform ${{ runner.os }}"
          exit 1
        fi
        mkdir download && cd download
        wget $SWIFTLINT_URL
      working-directory: ${{ github.action_path }}
    - name: Print Environment
      shell: bash
      run: |
        echo "Downloaded SwiftLint to ${{ env.SWIFTLINT_BINARY }}"
    - name: swiftlint
      run: ${{ github.action_path }}/swiftlint.sh ${{ inputs.args }}
      shell: bash
      working-directory: '${{ github.workspace }}/${{ inputs.working-directory }}'
