#
# This source file is part of the Stanford Biodesign for Digital Health open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#


name: 'SwiftLint Tool'
description: 'A tool to enforce Swift style and conventions using the official image.'
author: 'Andreas Bauer <mail@andi-bauer.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'terminal'
  color: 'green'
