name: 'SwiftLint'
description: 'A tool to enforce Swift style and conventions using the official image.'
author: 'Andreas Bauer <mail@andi-bauer.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'terminal'
  color: 'green'
