#
# This source file is part of the Stanford Biodesign for Digital Health open-source project
#
# SPDX-FileCopyrightText: 2023 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Docker Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  REUSE:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  DockerBuild:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker build -t action-swiftlint .
      - name: Exit Status on Errors
        run: |
          STATUS=$(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint &>/dev/null; echo $?)
          [[ $STATUS == "2" ]]
        working-directory: ./test/errors
        shell: bash
      - name: Exit Status on No lintable files
        run: |
          STATUS=$(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint &>/dev/null; echo $?)
          [[ $STATUS == "1" ]]
        working-directory: ./test/no-lintable-files
        shell: bash
      - name: Exit Status on Warnings
        run: |
          STATUS=$(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint &>/dev/null; echo $?)
          [[ $STATUS == "0" ]]
        working-directory: ./test/Warnings
        shell: bash
      - name: Exit Status on Warnings with `--strict`
        run: |
          STATUS=$(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint --strict &>/dev/null; echo $?)
          [[ $STATUS == "2" ]]
        working-directory: ./test/Warnings
        shell: bash
      - name: Output on Errors
        run: diff <(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint|sort) expected.txt
        working-directory: ./test/errors
        shell: bash
      - name: Output on Warnings
        run: diff <(docker run -v $(pwd):$(pwd) -w $(pwd) --rm action-swiftlint|sort) expected.txt
        working-directory: ./test/Warnings
        shell: bash
      - name: Output on Warnings with WORKING_DIRECTORY environment variable
        run: diff <(docker run -v $(pwd):$(pwd) -w $(pwd) --rm --env WORKING_DIRECTORY=Warnings action-swiftlint|sort) <(cat Warnings/expected.txt | sed -E 's/^(.*)file=(.*),(.*)/\1file=Warnings\/\2,\3/')
        working-directory: ./test
        shell: bash
