name: Docker Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  DockerLint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Lint
        uses: docker://replicated/dockerfilelint
        with:
          args: Dockerfile
